/**
 * Form Config Public API
 *
 * This module provides functions to fetch form configurations
 * for the Shopify loader script. It queries Firebase directly.
 */

import {
  collection,
  collectionGroup,
  doc,
  getDoc,
  getDocs,
  limit,
  orderBy,
  query,
  where,
} from "firebase/firestore";
import { db } from "../firebase";
import type { FormConfig, MetaPixelProfile } from "../../types/form";

export interface FormConfigResponse {
  formId: string;
  formName: string;
  userId?: string;
  assignment: {
    id: string;
    type: "store" | "product";
    storeId: string;
    productId?: string;
    productHandle?: string;
    priority: number;
  };
  store: {
    id: string;
    name: string;
    domain: string;
    platform: string;
  };
  config: FormConfig;
  pixels?: MetaPixelProfile[]; // Meta Pixel profiles
}

export interface FormConfigError {
  error: string;
  domain?: string;
}

/**
 * Get form config for a specific store/product
 *
 * @param domain - The Shopify store domain (e.g., "my-store.myshopify.com")
 * @param productId - Optional product ID for product-specific forms
 * @param productHandle - Optional product handle for URL matching
 */
export async function getFormConfig(
  domain: string,
  productId?: string,
  productHandle?: string
): Promise<FormConfigResponse | FormConfigError> {
  try {
    // Normalize domain - remove protocol and trailing slashes
    const normalizedDomain = domain
      .replace(/^https?:\/\//, "")
      .replace(/\/$/, "")
      .toLowerCase();

    // Find the store by URL
    let storeDoc = null;

    // Try exact match first
    const storesQuery = query(
      collectionGroup(db, "stores"),
      where("status", "==", "connected"),
      limit(50) // Get all connected stores and filter client-side
    );

    const storesSnapshot = await getDocs(storesQuery);

    for (const doc of storesSnapshot.docs) {
      const storeData = doc.data();
      const storeUrl = (storeData.url || "")
        .toLowerCase()
        .replace(/^https?:\/\//, "")
        .replace(/\/$/, "");

      // Check if domain matches (with or without myshopify.com)
      if (
        storeUrl === normalizedDomain ||
        storeUrl === normalizedDomain.replace(".myshopify.com", "") ||
        `${storeUrl}.myshopify.com` === normalizedDomain
      ) {
        storeDoc = { id: doc.id, ...storeData };
        break;
      }
    }

    if (!storeDoc) {
      return { error: "Store not found", domain };
    }

    // Try to find product-specific assignment first
    let assignment = null;

    if (productId || productHandle) {
      const productAssignmentsQuery = query(
        collection(db, "users", storeDoc.userId, "assignments"),
        where("storeId", "==", storeDoc.id),
        where("assignmentType", "==", "product"),
        where("isActive", "==", true),
        limit(100)
      );

      const productAssignments = await getDocs(productAssignmentsQuery);

      for (const doc of productAssignments.docs) {
        const data = doc.data();
        if (
          (productId && data.productId === productId) ||
          (productHandle && data.productHandle === productHandle)
        ) {
          assignment = { id: doc.id, ...data };
          break;
        }
      }
    }

    // Fall back to store-level assignment
    if (!assignment) {
      const storeAssignmentsQuery = query(
        collection(db, "users", storeDoc.userId, "assignments"),
        where("storeId", "==", storeDoc.id),
        where("assignmentType", "==", "store"),
        where("isActive", "==", true),
        orderBy("priority", "desc"),
        limit(1)
      );

      const storeAssignments = await getDocs(storeAssignmentsQuery);

      if (!storeAssignments.empty) {
        const doc = storeAssignments.docs[0];
        assignment = { id: doc.id, ...doc.data() };
      }
    }

    if (!assignment) {
      return { error: "No form assignment found", domain };
    }

    // Get the form config
    const formRef = doc(db, "users", storeDoc.userId, "forms", assignment.formId);
    const formSnap = await getDoc(formRef);

    if (!formSnap.exists()) {
      return { error: "Form not found" };
    }

    const formData = formSnap.data();
    const config = (formData.config || {}) as FormConfig;

    // Fetch Meta Pixels if configured
    let pixels: MetaPixelProfile[] = [];
    if (config.addons?.metaPixelIds?.length && config.addons.metaPixelIds.length > 0) {
      try {
        const pixelIds = config.addons.metaPixelIds;
        // Firestore 'in' query is limited to 10 items.
        // For now, we assume < 10 pixels. If more, we might need multiple queries or client-side filtering (not ideal for loader).
        // Actually, fetching by doc ID is better if we have the IDs.
        // But the collection is meta_pixels. IDs in config are doc IDs or pixel IDs?
        // They should be doc IDs (UUIDs) generated by us.

        // Since we need to fetch specific docs, we can use getAll/getDocs with where 'in' documentId() - but firebase client SDK doesn't support 'in' with documentId easily in all versions.
        // Easiest: Fetch all pixels for the store owner? No, we don't know the owner ID easily here without querying store again.
        // We have storeDoc.userId (if it exists).

        // Let's try fetching by document IDs using where('__name__', 'in', ...) or just individual gets in parallel.
        // Parallel gets are fine for small numbers.

        const pixelsCollection = collection(db, "meta_pixels");
        // We can't query by ID list easily without 'in' and 10 limit.
        // Let's use individual getDoc calls, it's robust.

        const pixelPromises = pixelIds.map((id: string) => getDoc(doc(db, "users", storeDoc.userId, "meta_pixels", id)));
        const pixelSnaps = await Promise.all(pixelPromises);

        pixels = pixelSnaps
          .filter(snap => snap.exists())
          // @ts-ignore - The database stores the pixel ID under some field, assuming 'pixelId'
          .map(snap => ({ id: snap.id, pixelId: snap.data()?.pixelId || snap.id, ...snap.data() } as MetaPixelProfile));

      } catch (e) {
        console.warn("Error fetching meta pixels:", e);
        // Don't fail the whole load if pixels fail
      }
    }



    return {
      formId: assignment.formId,
      formName: formData.name,
      userId: storeDoc.userId,
      assignment: {
        id: assignment.id,
        type: assignment.assignmentType,
        storeId: assignment.storeId,
        productId: assignment.productId,
        productHandle: assignment.productHandle,
        priority: assignment.priority,
      },
      store: {
        id: storeDoc.id,
        name: storeDoc.name,
        domain: normalizedDomain,
        platform: storeDoc.platform,
      },
      config: formData.config,
      pixels,
    };
  } catch (error: unknown) {
    console.error("Error fetching form config:", error);
    return { error: error instanceof Error ? error.message : "Failed to fetch form config" };
  }
}

/**
 * Check if a response is an error
 */
export function isFormConfigError(
  response: FormConfigResponse | FormConfigError
): response is FormConfigError {
  return "error" in response;
}
