// Theme presets for comprehensive styling - Complete theme variations

export interface ThemePreset {
  id: string;
  name: string;
  category: "light" | "dark" | "vibrant" | "minimal" | "basic";
  accentColor: string;
  ctaColor: string;
  formBackground: string;
  textColor: string;
  headingColor: string;
  borderRadius: string;
  // Input Colors
  inputBackground?: string;
  inputBorderColor?: string;
  inputTextColor?: string;
  inputPlaceholderColor?: string;
  // Card Colors
  cardBackground?: string;
  cardBorderColor?: string;
  preview?: string; // Optional gradient preview
  // Spacings for compact themes
  sectionSpacing?: number;
  sectionPadding?: number;
  inputSpacing?: number;
  sectionMarginTop?: number;
  sectionMarginBottom?: number;
}

// Helper function to calculate if background is dark
const isDark = (hex: string): boolean => {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  const brightness = (r * 299 + g * 587 + b * 114) / 1000;
  return brightness < 128;
};

export const THEME_PRESETS: ThemePreset[] = [
  // ===== LIGHT THEMES =====
  {
    id: "indigo",
    name: "Indigo Pro",
    category: "light",
    accentColor: "#6366f1",
    ctaColor: "#4f46e5",
    formBackground: "#ffffff",
    textColor: "#1e293b",
    headingColor: "#0f172a",
    borderRadius: "12px",
    cardBackground: "#f8fafc",
    cardBorderColor: "#e2e8f0",
  },
  {
    id: "emerald",
    name: "Émeraude",
    category: "light",
    accentColor: "#10b981",
    ctaColor: "#059669",
    formBackground: "#ffffff",
    textColor: "#1e293b",
    headingColor: "#0f172a",
    borderRadius: "12px",
    cardBackground: "#f0fdf4",
    cardBorderColor: "#bbf7d0",
  },
  {
    id: "blue",
    name: "Bleu Royal",
    category: "light",
    accentColor: "#3b82f6",
    ctaColor: "#2563eb",
    formBackground: "#ffffff",
    textColor: "#1e293b",
    headingColor: "#0f172a",
    borderRadius: "12px",
    cardBackground: "#eff6ff",
    cardBorderColor: "#bfdbfe",
  },
  {
    id: "violet",
    name: "Violet Dream",
    category: "light",
    accentColor: "#8b5cf6",
    ctaColor: "#7c3aed",
    formBackground: "#ffffff",
    textColor: "#1e293b",
    headingColor: "#0f172a",
    borderRadius: "12px",
    cardBackground: "#f5f3ff",
    cardBorderColor: "#ddd6fe",
  },
  {
    id: "rose",
    name: "Rose Vibrant",
    category: "vibrant",
    accentColor: "#ec4899",
    ctaColor: "#db2777",
    formBackground: "#ffffff",
    textColor: "#1e293b",
    headingColor: "#0f172a",
    borderRadius: "12px",
    cardBackground: "#fdf2f8",
    cardBorderColor: "#fbcfe8",
  },
  {
    id: "amber",
    name: "Ambre Warm",
    category: "vibrant",
    accentColor: "#f59e0b",
    ctaColor: "#d97706",
    formBackground: "#ffffff",
    textColor: "#1e293b",
    headingColor: "#0f172a",
    borderRadius: "12px",
    cardBackground: "#fffbeb",
    cardBorderColor: "#fde68a",
  },
  {
    id: "teal",
    name: "Océan",
    category: "light",
    accentColor: "#14b8a6",
    ctaColor: "#0d9488",
    formBackground: "#ffffff",
    textColor: "#1e293b",
    headingColor: "#0f172a",
    borderRadius: "12px",
    cardBackground: "#f0fdfa",
    cardBorderColor: "#99f6e4",
  },
  {
    id: "red",
    name: "Rouge Bold",
    category: "vibrant",
    accentColor: "#ef4444",
    ctaColor: "#dc2626",
    formBackground: "#ffffff",
    textColor: "#1e293b",
    headingColor: "#0f172a",
    borderRadius: "12px",
    cardBackground: "#fef2f2",
    cardBorderColor: "#fecaca",
  },
  {
    id: "coral",
    name: "Corail",
    category: "vibrant",
    accentColor: "#f97316",
    ctaColor: "#ea580c",
    formBackground: "#ffffff",
    textColor: "#1e293b",
    headingColor: "#0f172a",
    borderRadius: "14px",
    cardBackground: "#fff7ed",
    cardBorderColor: "#fed7aa",
  },
  {
    id: "cyan",
    name: "Cyan Fresh",
    category: "light",
    accentColor: "#06b6d4",
    ctaColor: "#0891b2",
    formBackground: "#ffffff",
    textColor: "#1e293b",
    headingColor: "#0f172a",
    borderRadius: "12px",
    cardBackground: "#ecfeff",
    cardBorderColor: "#a5f3fc",
  },
  {
    id: "fuchsia",
    name: "Fuchsia Pop",
    category: "vibrant",
    accentColor: "#d946ef",
    ctaColor: "#c026d3",
    formBackground: "#ffffff",
    textColor: "#1e293b",
    headingColor: "#0f172a",
    borderRadius: "16px",
    cardBackground: "#fdf4ff",
    cardBorderColor: "#f0abfc",
  },
  {
    id: "lime",
    name: "Lime Energy",
    category: "vibrant",
    accentColor: "#84cc16",
    ctaColor: "#65a30d",
    formBackground: "#ffffff",
    textColor: "#1e293b",
    headingColor: "#0f172a",
    borderRadius: "12px",
    cardBackground: "#f7fee7",
    cardBorderColor: "#bef264",
  },
  // ===== MINIMAL THEMES =====
  {
    id: "slate",
    name: "Ardoise Pro",
    category: "minimal",
    accentColor: "#64748b",
    ctaColor: "#1e293b",
    formBackground: "#ffffff",
    textColor: "#1e293b",
    headingColor: "#0f172a",
    borderRadius: "12px",
    cardBackground: "#f8fafc",
    cardBorderColor: "#e2e8f0",
  },
  {
    id: "light",
    name: "Light Minimal",
    category: "minimal",
    accentColor: "#6366f1",
    ctaColor: "#4f46e5",
    formBackground: "#f8fafc",
    textColor: "#334155",
    headingColor: "#0f172a",
    borderRadius: "8px",
    cardBackground: "#ffffff",
    cardBorderColor: "#e2e8f0",
  },
  {
    id: "soft_gray",
    name: "Gris Doux",
    category: "minimal",
    accentColor: "#6b7280",
    ctaColor: "#374151",
    formBackground: "#f9fafb",
    textColor: "#374151",
    headingColor: "#111827",
    borderRadius: "10px",
    cardBackground: "#ffffff",
    cardBorderColor: "#e5e7eb",
  },
  {
    id: "warm_neutral",
    name: "Neutral Warm",
    category: "minimal",
    accentColor: "#78716c",
    ctaColor: "#57534e",
    formBackground: "#fafaf9",
    textColor: "#44403c",
    headingColor: "#1c1917",
    borderRadius: "12px",
    cardBackground: "#ffffff",
    cardBorderColor: "#e7e5e4",
  },
  // ===== DARK THEMES =====
  {
    id: "dark",
    name: "Noir Élégant",
    category: "dark",
    accentColor: "#6366f1",
    ctaColor: "#4f46e5",
    formBackground: "#0f172a",
    textColor: "#e2e8f0",
    headingColor: "#f8fafc",
    borderRadius: "12px",
    inputBackground: "#1e293b",
    inputBorderColor: "#334155",
    inputTextColor: "#f1f5f9",
    inputPlaceholderColor: "#94a3b8",
    cardBackground: "#1e293b",
    cardBorderColor: "#334155",
  },
  {
    id: "dark_emerald",
    name: "Dark Emerald",
    category: "dark",
    accentColor: "#10b981",
    ctaColor: "#059669",
    formBackground: "#0f172a",
    textColor: "#e2e8f0",
    headingColor: "#f8fafc",
    borderRadius: "12px",
    inputBackground: "#1e293b",
    inputBorderColor: "#334155",
    inputTextColor: "#f1f5f9",
    inputPlaceholderColor: "#94a3b8",
    cardBackground: "#1e293b",
    cardBorderColor: "#334155",
  },
  {
    id: "dark_rose",
    name: "Dark Rose",
    category: "dark",
    accentColor: "#ec4899",
    ctaColor: "#db2777",
    formBackground: "#18181b",
    textColor: "#e4e4e7",
    headingColor: "#fafafa",
    borderRadius: "14px",
    inputBackground: "#27272a",
    inputBorderColor: "#3f3f46",
    inputTextColor: "#f4f4f5",
    inputPlaceholderColor: "#a1a1aa",
    cardBackground: "#27272a",
    cardBorderColor: "#3f3f46",
  },
  {
    id: "midnight_blue",
    name: "Midnight Blue",
    category: "dark",
    accentColor: "#3b82f6",
    ctaColor: "#2563eb",
    formBackground: "#0c0a09",
    textColor: "#d6d3d1",
    headingColor: "#fafaf9",
    borderRadius: "12px",
    inputBackground: "#1c1917",
    inputBorderColor: "#292524",
    inputTextColor: "#e7e5e4",
    inputPlaceholderColor: "#a8a29e",
    cardBackground: "#1c1917",
    cardBorderColor: "#292524",
  },
  {
    id: "charcoal",
    name: "Charcoal Pro",
    category: "dark",
    accentColor: "#f59e0b",
    ctaColor: "#d97706",
    formBackground: "#171717",
    textColor: "#d4d4d4",
    headingColor: "#f5f5f5",
    borderRadius: "10px",
    inputBackground: "#262626",
    inputBorderColor: "#404040",
    inputTextColor: "#e5e5e5",
    inputPlaceholderColor: "#a3a3a3",
    cardBackground: "#262626",
    cardBorderColor: "#404040",
  },
  {
    id: "ocean_night",
    name: "Ocean Night",
    category: "dark",
    accentColor: "#06b6d4",
    ctaColor: "#0891b2",
    formBackground: "#0f1419",
    textColor: "#cbd5e1",
    headingColor: "#f1f5f9",
    borderRadius: "16px",
    inputBackground: "#1a2634",
    inputBorderColor: "#2d3f50",
    inputTextColor: "#e2e8f0",
    inputPlaceholderColor: "#8899a6",
    cardBackground: "#1a2634",
    cardBorderColor: "#2d3f50",
  },
  // ===== GRADIENT/SPECIAL THEMES =====
  {
    id: "gradient",
    name: "Gradient Modern",
    category: "vibrant",
    accentColor: "#8b5cf6",
    ctaColor: "#6366f1",
    formBackground: "#ffffff",
    textColor: "#1e293b",
    headingColor: "#0f172a",
    borderRadius: "16px",
    cardBackground: "#faf5ff",
    cardBorderColor: "#e9d5ff",
  },
  {
    id: "soft_pink",
    name: "Soft Pink",
    category: "light",
    accentColor: "#f472b6",
    ctaColor: "#ec4899",
    formBackground: "#fdf2f8",
    textColor: "#831843",
    headingColor: "#500724",
    borderRadius: "20px",
    cardBackground: "#ffffff",
    cardBorderColor: "#fbcfe8",
  },
  {
    id: "forest",
    name: "Forest Green",
    category: "light",
    accentColor: "#22c55e",
    ctaColor: "#16a34a",
    formBackground: "#f0fdf4",
    textColor: "#166534",
    headingColor: "#14532d",
    borderRadius: "12px",
    cardBackground: "#ffffff",
    cardBorderColor: "#bbf7d0",
  },
  {
    id: "sky_blue",
    name: "Sky Blue",
    category: "light",
    accentColor: "#0ea5e9",
    ctaColor: "#0284c7",
    formBackground: "#f0f9ff",
    textColor: "#0c4a6e",
    headingColor: "#082f49",
    borderRadius: "14px",
    cardBackground: "#ffffff",
    cardBorderColor: "#bae6fd",
  },
  // ===== BASIC/COMPACT THEMES =====
  {
    id: "basic_light",
    name: "Basic Light",
    category: "basic",
    accentColor: "#2563eb",
    ctaColor: "#1d4ed8",
    formBackground: "#ffffff",
    textColor: "#334155",
    headingColor: "#0f172a",
    borderRadius: "4px",
    inputBackground: "#f8fafc",
    inputBorderColor: "#cbd5e1",
    inputTextColor: "#0f172a",
    inputPlaceholderColor: "#94a3b8",
    cardBackground: "#ffffff",
    cardBorderColor: "#cbd5e1",
    sectionSpacing: 12,
    sectionPadding: 16,
    inputSpacing: 8,
  },
  {
    id: "basic_gray",
    name: "Basic Gray",
    category: "basic",
    accentColor: "#4b5563",
    ctaColor: "#374151",
    formBackground: "#f9fafb",
    textColor: "#1f2937",
    headingColor: "#111827",
    borderRadius: "6px",
    inputBackground: "#ffffff",
    inputBorderColor: "#d1d5db",
    inputTextColor: "#111827",
    inputPlaceholderColor: "#9ca3af",
    cardBackground: "#ffffff",
    cardBorderColor: "#e5e7eb",
    sectionSpacing: 10,
    sectionPadding: 12,
    inputSpacing: 6,
  },
  {
    id: "basic_clean",
    name: "Basic Clean",
    category: "basic",
    accentColor: "#0ea5e9",
    ctaColor: "#0284c7",
    formBackground: "#ffffff",
    textColor: "#1e293b",
    headingColor: "#0f172a",
    borderRadius: "0px", // Ultra sharp
    inputBackground: "#ffffff",
    inputBorderColor: "#e2e8f0",
    inputTextColor: "#0f172a",
    inputPlaceholderColor: "#cbd5e1",
    cardBackground: "#ffffff",
    cardBorderColor: "#e2e8f0",
    sectionSpacing: 8,
    sectionPadding: 10,
    inputSpacing: 6,
  },
];

// Group presets by category for better organization in UI
export const PRESET_CATEGORIES = {
  light: {
    label: "Thèmes Clairs",
    description: "Fond blanc avec couleurs d'accent",
  },
  dark: {
    label: "Thèmes Sombres",
    description: "Fond sombre pour un look moderne",
  },
  vibrant: {
    label: "Thèmes Vibrants",
    description: "Couleurs vives et énergiques",
  },
  minimal: {
    label: "Thèmes Minimaux",
    description: "Design épuré et professionnel",
  },
  basic: {
    label: "Thèmes Basiques",
    description: "Ultra-rapide, compact et sans fioritures",
  },
};
